//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synchronic_World
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [Serializable]
    [DataContract]
    public partial class Person
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public string NickName { get; set; }
        [DataMember]
        public string Password { get; set; }
        [DataMember]
        public int Event_Id { get; set; }
    }
}
